### ISSUE TITLE
Use a JS bundler, put HTML templates in seperate files

### ISSUE THREAD

**Issue by moeenio** [cobwebdev/whittr#7]
- Use a JavaScript bundler such as Parcel for the front-end code
- Load the front-end librairies from NPM
- Turn the HTML into Nunjucks (or something else) templates in seperate files and use the main template file as the entry point for the bundler (see [here](https://github.com/chocolateboy/parcel-plugin-nunjucks#synopsis for Parcel)

**Comment by locness3** [comment]
and get front-end libs from npm

**Comment by ghost** [comment]
> and get front-end libs from npm

Yeah that's fine! If it will work better than it's great. Thank you for your help

**Comment by locness3** [comment]
Okay. I think I will go with rollup.

**Comment by moeenio** [comment]
Please wait until #10 is merged

And maybe until some later release

**Comment by moeenio** [comment]
I've edited my initial comment. Is everything okay with you @whyadamsalt ?

**Comment by moeenio** [comment]
> Load the front-end librairies from NPM

btw this can already be done without bundler stuff

**Comment by ghost** [comment]
Ah alright. Well @kingsley-einstein should be able to take it from here

**Comment by moeenio** [comment]
While loading libs from npm should definitely be done, i'm really unsure about the rest.
